/*CREATE TABLE*/
CREATE TABLE ACCOUNT
(
 ACC_NO varchar2(5),
    Name VARCHAR2(30),
    City varchar2(20),
    Balance number(10,2),
    loan_taken varchar2(5)
);
/*INSERT DATA IN TABLE  */
INSERT INTO ACCOUNT VALUES('A001','Patel jigar','Mehsana',50000,'Yes','SBI',12345);
INSERT INTO ACCOUNT VALUES('A002','Patel Ramesh','Mehsana',50000,'Yes','PNB',34576); 
INSERT INTO ACCOUNT VALUES('A003','Dave Hardik','Ahmedabad',75000,'NO','KOTAK MAHINDRA',67895);
INSERT INTO ACCOUNT VALUES('A004','Soni Hetal','Ahmedabad',100000,'No','KENRA BANK',48735);
INSERT INTO ACCOUNT VALUES('A005','Sony Atul','Vadodara',100000,'Yes','ICICI',98706);
/*ADD "NEW COLUMN" IN TABLE WITH ALTER KEYWORDS  */
ALTER TABLE ACCOUNT ADD BANK_NAME VARCHAR2(45);
ALTER TABLE ACCOUNT ADD IFSC_CODE VARCHAR(20);
/*MODIFY "COLUMN DATATYPE" IN TABLE WITH ALTER KEYWORDS */
ALTER TABLE ACCOUNT MODIFY IFSC_CODE NUMBER(15);
/*RENAME "EXISTING COLUMN NAME" TO NEW COLUMN NAME IN TABLE WITH ALTER KEYWORDS  */
ALTER TABLE ACCOUNT RENAME COLUMN IFSC_CODE TO ACC_cODE;
/*DROP "ANY COLUMN NAME" FROM TABLE WITH ALTER KEYWORDS  */
ALTER TABLE ACCOUNT DROP COLUMN BANK_NAME;
/*RENAME EXISTING TABLE NAME WITH NEW TABLE NAME */
RENAME ACCOUNT TO ACCOUNT_DETAILS;
/*THIS IS QUERY FOR ACCESSING ALL THE DATA FROM THE SPECIFIED TABLE */
INSERT INTO ACCOUNT_DETAILS VALUES('A001','Patel jigar','Mehsana',50000,'Yes','SBI',12345);
INSERT INTO ACCOUNT_DETAILS VALUES('A002','Patel Ramesh','Mehsana',50000,'Yes','PNB',34576); 
INSERT INTO ACCOUNT_DETAILS VALUES('A003','Dave Hardik','Ahmedabad',75000,'NO','KOTAK MAHINDRA',67895);
INSERT INTO ACCOUNT_DETAILS VALUES('A004','Soni Hetal','Ahmedabad',100000,'No','KENRA BANK',48735);
INSERT INTO ACCOUNT_DETAILS VALUES('A005','Sony Atul','Vadodara',100000,'Yes','ICICI',98706);
/* SELECT "ALL ROWS AND ALL COLUMN" OF THE TABLE */
SELECT * FROM ACCOUNT_DETAILS;
/* SELECT ONLY ONE COLUM AND ALL ROW */
SELECT CITY FROM ACCOUNT_DETAILS;
/* SELECT SELECTED ROWS AND SELECTED COLUMN */
SELECT Acc_no ,NAME,Balance FROM ACCOUNT_DETAILS WHERE NAME='Patel Ramesh' ;
/* SELECT "ALL COLUMN AND DISPLAY SELECTED ROW ONLY" */
SELECT * FROM ACCOUNT_DETAILS WHERE NAME='Soni Hetal';
/*DESCRIBE/DESK IS USED FOR THE "SEEING THE STRUCTURE OF THE TABLE"  */
DESCRIBE ACCOUNT_DETAILS;
/* SELECT ONLY ONE COLUMN WITH CONDITIONS */
SELECT Acc_no FROM ACCOUNT_DETAILS WHERE BALANCE=100000;
/* SELECT ONLY ONE COLUMN AND CORRESPONDING ALL COLUMN */
SELECT CITY FROM ACCOUNT_DETAILS ;

SELECT * FROM ACCOUNT_DETAILS WHERE Acc_no='A001';
/* IF WE ARE UPDATING THE DATA THEN ON SAME COLUMN WE CAN NOT USE OPERATIONS. */
UPDATE ACCOUNT_DETAILS SET name='Patel Hiren' WHERE ACC_NO='A001';

UPDATE ACCOUNT_DETAILS set name='kothari nehal' AND city='patan' where ACC_NO='A005';