CREATE TABLE ACCOUNT_DEMO
(
    ACC_NO VARCHAR2(5),
    NAME VARCHAR(30),
    CITY VARCHAR2(20),
    BALANCE NUMBER(10,2),
    LOAN_TAKEN VARCHAR2(5)
);
INSERT INTO ACCOUNT_DEMO VALUES ('A001','Patel Jigar','Mehsana',50000,'Yes');
INSERT INTO ACCOUNT_DEMO VALUES ('A002','Patel Ramesh','Mehsana',50000,'Yes');
 INSERT INTO ACCOUNT_DEMO VALUES ('A003','Dave Hardik','Ahmedabad',750000,'No');
 INSERT INTO ACCOUNT_DEMO VALUES ('A004','Soni Hetal','Ahmedabad',100000,'No');
 INSERT INTO ACCOUNT_DEMO VALUES ('A005','Sony Atul','Vadodara',100000,'Yes');
 DESCRIBE ACCOUNT_DEMO;

 CREATE TABLE ACCOUNT_TEMP AS
   SELECT ACC_NO,NAME,BALANCE
   FROM ACCOUNT_DEMO;
 
SELECT * FROM ACCOUNT_TEMP;


 UPDATE ACCOUNT_DEMO set NAME='Kothari nehal',CITY='Patan' WHERE ACC_NO='A005';

ALTER TABLE ACCOUNT_DEMO Add Address VARCHAR2(20);

 SELECT * from ACCOUNT_DEMO WHERE LOAN_TAKEN='Yes';

 SELECT * from ACCOUNT_DEMO;

 RENAME ACCOUNT_DEMO TO ACCOUNT_MASTER;

 SELECT * from ACCOUNT_MASTER WHERE ACC_NO='A005';
 DELETE FROM ACCOUNT_MASTER WHERE ACC_NO='A004';
 DESCRIBE ACCOUNT_MASTER;
 SELECT * from ACCOUNT_MASTER;
 update ACCOUNT_MASTER set BALANCE=2*BALANCE;
 update ACCOUNT_MASTER set BALANCE=100000+BALANCE;
/*ASC/DESC ORDER OF DATA  */
 SELECT * from ACCOUNT_MASTER ORDER BY Balance DESC ;
 SELECT * from ACCOUNT_MASTER WHERE NAME like 'Da%' ;
 SELECT * from ACCOUNT_MASTER WHERE city like 'Ah%' ;
 SELECT * from ACCOUNT_MASTER WHERE Loan_taken like 'Y%' ;
 SELECT * from ACCOUNT_MASTER WHERE   ACC_NO like 'A%' ;
SELECT * from ACCOUNT_MASTER WHERE    BALANCE  like '1%' ;




