CREATE TABLE ACCOUNT_DBMS
(
 Acc_no VARCHAR2(5) PRIMARY KEY,
 NAME VARCHAR2(30) NOT NULL,
 CITY VARCHAR2(20) NOT NULL,
 BALANCE NUMBER(10,2) NOT NULL CHECK (BALANCE >=500),
 LOAN_TAKEN VARCHAR2(3)  CHECK (LOAN_TAKEN='YES' OR LOAN_TAKEN='NO') 
);
/*INSERT DATA IN TABLE  */
INSERT INTO ACCOUNT_DBMS VALUES('A001','jeetan kumar','Mehsana',50000,'Yes');
INSERT INTO ACCOUNT_DBMS VALUES('A003','Nitesh kumar','Ahmedabad',75000,'NO');
INSERT INTO ACCOUNT_DBMS VALUES('A004','brijesh kumar','Ahmedabad',100000,'No');
INSERT INTO ACCOUNT_DBMS VALUES('A005','nitesh','Vadodara',100000,'Yes');
INSERT INTO ACCOUNT VALUES('A002','raju kumar','Mehsana',50000,'Yes');
SELECT * from ACCOUNT_DBMS;