CREATE TABLE INSTALLMENT
(
    LOAN_no varchar2(5),
    INST_NO VARCHAR2(5),
    INST_DATE DATE,
    AMOUNT NUMBER(10,2)         

);
INSERT INTO INSTALLMENT VALUES('L001','I001',TO_DATE('2-02-04','DD-MM-YYYY'),15000);
INSERT INTO INSTALLMENT VALUES('L002','I002',TO_DATE('18-06-04','DD-MM-YYYY'),20000); 
INSERT INTO INSTALLMENT VALUES('L003','I003',TO_DATE('15-07-04','DD-MM-YYYY'),20000);

SELECT COUNT(*) FROM INSTALLMENT ;
UPDATE INSTALLMENT SET INST_DATE=TO_DATE('03-05-04','DD-MM-YYYY') WHERE INST_DATE=TO_DATE('02-02-04','DD-MM-YYYY');

UPDATE INSTALLMENT SET AMOUNT=AMOUNT-5000;

UPDATE INSTALLMENT SET AMOUNT=5000+AMOUNT WHERE LOAN_no='L003';

ALTER TABLE INSTALLMENT MODIFY LOAN_no VARCHAR2(7);
DELETE FROM INSTALLMENT WHERE INST_NO='I003';
DESCRIBE INSTALLMENT;
ALTER TABLE INSTALLMENT MODIFY INST_NO VARCHAR2(4);
select 'loan no:'||LOAN_NO||'  '||'amount:-'||10*AMOUNT||' '||'taken by you' from INSTALLMENT where LOAN_NO='L001' ;
DELETE FROM INSTALLMENT WHERE INST_NO='I002';
CREATE TABLE INSTALLMENT1 AS
   SELECT LOAN_no,INST_NO,INST_DATE,AMOUNT
   FROM INSTALLMENT;
   DESCRIBE INSTALLMENT1;