CREATE TABLE SCHOOL
(
    NAME VARCHAR2(30),
    MOB_NUM NUMBER
);

INSERT INTO SCHOOL VALUES('NITESH KUMAR',8945);
INSERT INTO SCHOOL VALUES('JEETAN KUMAR',4545);

SELECT * FROM SCHOOL;
TRUNCATE TABLE SCHOOL;
UPDATE  SCHOOL SET MOB_NUM=1234567895 WHERE NAME='NITESH KUMAR';
RENAME SCHOOL to school1;
DESCRIBE SCHOOL1;